version: '3.8'

services:
  app:
    container_name: automacao-app
    build:
      context: .
    volumes:
      - ./:/app
    command: yarn start
    ports:
      - 8080:8080

  db:
    image: mysql
    container_name: automacao-db
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: automacao
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql